language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo pip install --upgrade conda
install:
  # install deps
  - sudo conda init
  - deps='pip numpy pandas requests nose numpydoc sphinx pep8'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
  # install our own package into the environment
  - "pip install ."
  # Download spark 1.0.0
  - "wget http://d3kbcqa49mib13.cloudfront.net/spark-1.0.0-bin-hadoop2.tgz"
  - "tar -xvf spark-1.0.0-bin-hadoop2.tgz"
  - "export SPARK_HOME=./spark-1.0.0-bin-hadoop2/"
script:
  - "./run-tests"
  - "pep8 sparklingpandas/"
